### ISSUE TITLE
Slow performance with large manifests

### ISSUE THREAD

**Issue by luan** [luan/vim-bosh#4]
luan/vimfiles#77

**Comment by luan** [comment]
The issue here is that `boshtags` is traversing the home directory recursively.

**Comment by luan** [comment]
BTW, this has nothing to do with the size of the manifest but with the size of your current working directory.

**Comment by benmoss** [comment]
I was trying to figure out what was going wrong and traced vim to see that it was `boshtags` taking forever. It was running `/Users/pivotal/.gotools/boshtags -f /var/folders/sw/myvs9lb53sq3k7_y6f_9kzfw0000gn/T/vdpaxWi/35 -R /Users/pivotal/workspace`.

I tried running that and it printed out a ton of `couldn't read input file: EOF` before finally:

```
panic: regexp: Compile("^          \xf5\x18\x00\x00\x00+\x00\x00\x00[- ] alias: (.*)"): error parsing regexp: invalid UTF-8: `�+[- ] alias: (.*)`

goroutine 1 [running]:
panic(0xd6180, 0xc42037cf20)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
regexp.MustCompile(0xc420e64360, 0x24, 0x1)
	/usr/local/opt/go/libexec/src/regexp/regexp.go:237 +0x17a
main.(*tagParser).parse(0xc42006bca0, 0x1672c0, 0xc42002a560)
	/Users/pivotal/.vim/gopath/src/github.com/luan/boshtags/parser.go:143 +0x1068
main.Parse(0xc420251b90, 0x70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/pivotal/.vim/gopath/src/github.com/luan/boshtags/parser.go:39 +0x170
main.main()
	/Users/pivotal/.vim/gopath/src/github.com/luan/boshtags/main.go:176 +0x1b1
```

Probably is just because it was searching my entire `~/workspace` but still :man_shrugging:
